### ISSUE TITLE
Réforme mes aides pour projection des aides calculées sur une période > 1 mois

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-france#11]
Cette issue fait suite à la discussion initiée par @benjello  sur https://github.com/openfisca/openfisca-france/pull/244

Dans `cmu.py` on a :

``` python
aspa = simulation.calculate('aspa', this_month)
[...]
res += 12 * (aspa + ass + asi + af + cf + asf)
```

Ceci permet, dans le contexte de mes-aides, d'obtenir une estimation de la somme annuelle de prestations qui sont calculées uniquement pour le mois en cours, et qui ne sont pas capturées pour les mois précédents. 
C'est une idiosyncrasie de mes-aides qui dans l'idéal ne devrait pas se trouver dans le code openfisca, mais aujourd'hui nous n'avons pas de stratégie alternative. 
Une solution serait de pouvoir dire à Openfisca que, pour la simulation, certaines variables ne doivent être calculées que pour le mois en cours, et doivent être estimées identiques pour les mois précédents. 

Suite à notre discussion avec @eraviart et @jdesboeufs aujourd'hui, on aimerait pouvoir prendre un moment pour définir une solution qui tienne compte des contraintes côté mes-aides et Openfisca. @benjello , est ce que tu as le temps de passer au SGMAP prochainement ?

**Comment by benjello** [comment]
@fpagnoux @eraviart @jdesboeufs je passe quand vous voulez. Je pense que la solution est de mettre dans openfisca ce qui se rapproche plus de la loi et de me mettre dans un objet Reform les idiosyncrasie de mes-aides.

**Comment by fpagnoux** [comment]
Oui c'est une solution.

Est-ce que vous êtes disponibles demain matin ou après-midi ? 
@eraviart @benjello @jdesboeufs

**Comment by benjello** [comment]
Plutôt le matin pour moi

**Comment by fpagnoux** [comment]
Ok pour moi, @eraviart ça te va ?

**Comment by eraviart** [comment]
oui

**Comment by fpagnoux** [comment]
Issue en standby: on va capturer dans mes-aides les aides perçues dans le passé,  donc on n'aura plus besoin de les estimer comme aujourd'hui sur les 12 derniers mois. Cela devrait nous permettre de nous aligner avec Openfisca sur quelque chose de propre sans passer par une réforme.
