### ISSUE TITLE
Évaluation forfaitaire pour les travailleurs non salariés

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-france#16]
En tant que travailleur non salarié ayant subi un changement de situation depuis n-2,
Je peux bénéficier d'une évaluation forfaitaire de mes ressources,
Pour le calcul de mon AL

**Comment by MattiSG** [comment]
Définition faite dans sgmap/mes-aides-api#34 :

> Pour un TNS qui perçoit des ressources pro en m-1 et dont les RNC N-2 sont < 1015 fois le SMIC horaire du 31/12 de l'année N-2, on applique une [évaluation forfaitaire](http://legislation.openfisca.fr/variables/aide_logement_base_ressources_eval_forfaitaire) de ses ressources.
> La base ressources à prendre en compte dans ce cas est égale à 1500 \* SMIC horaire au 1er juillet qui précède la date d'ouverture du droit (ici de la simulation).
> Test : https://mes-aides.gouv.fr/tests/55c0ee462cdf295972b4f19f/show

**Comment by fpagnoux** [comment]
@HelaG,
Si je comprends bien la règle expliquée dans le test : 
Si un TNS avait des revenus faibles en N-2, et une activité en M-1, on lui compte comme ressources un montant fixe qui ne dépend pas de ses ressources actuelles ?

**Comment by fpagnoux** [comment]
Ok, ça semble confirmé [ici](http://www.senat.fr/questions/base/2010/qSEQ101216472.html).

**Comment by fpagnoux** [comment]
Il reste un écart sur le test après l'évaluation forfaitaire...

**Comment by fpagnoux** [comment]
Fixed, il fallait juste bien différencier le SMIC N-2 pour le plancher de ressource, et le SMIC de juillet dernier pour l'évaluation forfaitaire.
