### ISSUE TITLE
Pouvoir déclarer des jumeaux

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-france#21]
En tant que demandeur, 
Je peux déclarer mes enfants jumeaux, nés le même jour, sans faire planter Openfisca
pour obtenir un résultat

**Comment by fpagnoux** [comment]
Faux diagnostic, les jumeaux sont innocents. 
Le vrai problème: Openfisca plante quand on lui envoie une personne fiscalement à charge non handicapée dont l'âge est supérieur ou égal à 25 ans. 
Dans notre cas, comme nous ne capturons pas de toute façon les enfants de strictement plus de 25 ans,  le problème se pose seulement pour un enfant de 25 ans exactement. 

Je vais me renseigner auprès d'Openfisca pour éclaircir ce point et trouver une solution.

**Comment by MattiSG** [comment]
> Faux diagnostic, les jumeaux sont innocents.

:smile: 

GG !
