### ISSUE TITLE
Mettre à jour le barème des AF

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-france#24]
En tant que bénéficiaire potentiel faisant une simulation au 1er juillet 2015,
Je peux bénéficier du nouveau barème,
Pour avoir une simulation à jour
- [x] Twitter 
- [x] Wiki

**Comment by fpagnoux** [comment]
Voir discussion dans la PR

**Comment by fpagnoux** [comment]
Reste  à faire:
- [x] Mettre à jour les tests sur le serveur de prod en faisant tourner le script de migration
- [x] Communication

**Comment by MattiSG** [comment]
@fpagnoux Mettre à jour openfisca/openfisca-france#284 avec la dernière version des tests.

**Comment by fpagnoux** [comment]
Done.

**Comment by MattiSG** [comment]
https://twitter.com/mesaides/status/618825870736781312
