### ISSUE TITLE
PLF - Proposer l'aide aux propriétaires ayant un crédit

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-france#26]
En tant que propriétaire remboursant un crédit immobilier et respectant les conditions familiales et de ressources,
Je me vois proposer l'aide Paris Logement Famille,
Pour savoir que j'y suis éligible

**Comment by fpagnoux** [comment]
Besoin de clarification de la MdP, car "le montant de l'aide ne peut être supérieur à la charge mensuelle nette de logement, réellement supportée par le foyer." => pas clair pour un propriétaire.

**Comment by HelaG** [comment]
Communication [twitter](https://twitter.com/MesAides/status/625982397738258432) et Mairie de Paris.
