### ISSUE TITLE
Prendre en compte la garde alternée pour les AF

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-france#27]
En tant que demandeur ayant des enfants en garde alternée, 
Je peux avoir une estimation juste de mon droit aux AF

**Comment by fpagnoux** [comment]
Fait suite à sgmap/mes-aides-ui#1

**Comment by fpagnoux** [comment]
@HelaG : 
Je n'ai rien trouvé sur la garde alternée dans le wiki. De ce que j'ai lu [ailleurs](http://www.dossierfamilial.com/famille/couple/garde-alternee-les-consequences-sur-les-prestations-familiales-et-les-impots-57116), les parents ayant un enfant en garde alternée peuvent se répartir les AF selon la formule suivante:

> Conséquence : la prestation versée à chacun des parents est égale au montant des allocations familiales dues pour le total des enfants à charge multiplié par le rapport entre le nombre "moyen" d’enfants et le nombre total d’enfants. Attention toutefois,  les allocations familiales ne sont dues qu’à partir du deuxième enfant à charge. Le parent n’ayant qu’un seul enfant à charge ne peut y prétendre.
> 
> Exemple : vous avez trois enfants. Les deux petits vivent "à plein-temps" avec vous et l’aîné réside la moitié de la semaine au domicile de l’autre parent. Vous percevrez 83,33 % des allocations familiales prévues pour une famille de trois enfants, soit 100 % des allocations x (2,5 [nombre "moyen" d’enfants : 2 pour les derniers et 0,5 pour l’aîné en garde alternée]/3 [nombre total d’enfants]).

Mais dans sgmap/mes-aides-ui#1, un utilisateur nous signale qu'en ayant un enfant à taux plein plus un en garde alternée, il n'a droit à rien car "moins de deux enfants".  Il a créé un test [ici](https://mes-aides.gouv.fr/tests/553695fc5a5c6d762da9ba5a/show).

Est-ce que tu es sais plus ? 

Merci !

**Comment by HelaG** [comment]
@fpagnoux

Anne-Laure avait commencé à creuser la question [ici](https://wiki.openfisca.fr/index.php/Questions_transverses#Garde_altern.C3.A9e).

Et l'art 2 de ce [décret](http://legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000466994&dateTexte=&categorieLien=id) explique effectivement le calcul d'un "coefficient de prise en charge des enfants". 

On pourrait calculer ce coefficient pour une plus grande fiabilité des résultats sur les prestations familiales.

Reste à savoir comment traiter le cas des  "accords" entre parents. 
On peut:
- soit poser la question dès le 3ème enfant déclaré quand on capture une situation de garde alternée;
- soit appliquer systématiquement le coeff et informer les parents en sortie de simulation "nous avons calculé votre droit aux prestations familiales en fonction de la situation décrite, sans tenir compte d'éventuels accords entre les parents allocataires".

**Comment by fpagnoux** [comment]
Il me semble qu'on a pris la décision suivante :
- Appliquer systématiquement le coefficient 
- Disclaimer comme quoi on ne tient pas compte des accords

**Comment by fpagnoux** [comment]
@helag

Je viens d'implémenter la règle suivante : 

Pour une famille qui a n enfants, dont k en garde alternée, alors la famille percevra le montant suivant : 
AF pour n enfants x (1 - 0.5k/n)

Un point reste ambigu : qu'est ce qui se passe si le nombre d'enfant "moyen" est inférieur à 2 ? Par exemple si une famille a 1 enfant à taux plein + 1 en g.a, ou 3 enfants en g.a.

D'après le témoignage de stephanecolson, la CAF ne verserait pas d'AF dans ce cas. Mais je ne vois pas de telle règle dans le décret. Est-ce qu'on peut demander à quelqu'un d'avoir des précisions ?

**Comment by HelaG** [comment]
Retour de la DSS qui confirme notre compréhension du sujet :

Dès qu'il y a deux enfants à charge, la famille ouvre droit aux allocations familiales quelle que soit la valeur du coefficient (et donc du nombre moyen d'enfants intervenant dans ce calcul) résultant des règles définies à l'article R. 521-3 CSS : en effet, il s'agit d'un paramètre de calcul des AF et de la majoration pour âge en cas de présence dans le foyer d'un ou plusieurs enfants en résidence alternée. 

Exemple de calcul du coefficient prévu à l'article R. 521-3 CSS dans le cas d'une famille ayant un enfant en résidence alternée et un autre enfant "à temps plein" ouvrant droit aux AF : 

L'enfant en résidence alternée compte pour 0,5 enfant à charge 
L'autre enfant compte pour 1 enfant à charge 
Détermination du nombre moyen d'enfants  = 1 +0,5 = 1,5 enfants à charge 
Nombre total d’enfants pour ce foyer = 2 enfants 
Coefficient servant au calcul du montant des allocations familiales dû au foyer = 1,5/2.

**Comment by HelaG** [comment]
- [x] Refuser le [test](https://mes-aides.gouv.fr/tests/553695fc5a5c6d762da9ba5a/show?keyword=garde%20altern%C3%A9e)
- [x] Informer Stephane Colson

**Comment by fpagnoux** [comment]
Déployé aujourd’hui. Attention, il n'y a pas de test pour le moment.

**Comment by HelaG** [comment]
- [x] Créer des tests
- [x] Informer Mme Bussiere

**Comment by HelaG** [comment]
Tests créés :
- [cas simple d'une garde alternée 2 enfants pas de majoration](https://mes-aides.gouv.fr/tests/5631fdc7a93fb89045fadc4d/show)
- [Test vert - application du coefficient de répartition sur l'AF de base et pas la majoration](https://mes-aides.gouv.fr/tests/56322251c13af18e45e5ce91/show)
- [Test rouge - 3 enfants dont un de plus de 14 ans en garde alternée](https://mes-aides.gouv.fr/tests/5631ffd49506438345b55b10/show) (en cas de résidence alternée de l'enfant ouvrant droit à la majoration pour âge, le montant de la majoration est divisée par 2)
- [Test rouge - 3 enfants dont 2 en garde alternée (dont 1 de plus de 14 ans)](https://mes-aides.gouv.fr/tests/563227d6c13af18e45e5cea0/show?keyword=af&keyword=garde%20altern%C3%A9e)
  Connected to #37
