### ISSUE TITLE
Nouveau barême pour la bourse de collège 2015/2016

### ISSUE THREAD

**Issue by Flightan** [sgmap/openfisca-france#28]
Taux et barème pour l'attribution d'une bourse de collège en 2015-2016:

| Revenus annuels | 1 enfant | 2 enfants | 3 enfants | 4 enfants | 5 enfants | par enfant suppl. |
| --- | --- | --- | --- | --- | --- | --- |
| Plafond annuel pour le taux 1 : 84 € | 14 674 | 18 061 | 21 447 | 24 834 | 28 220 | 3 386,4 |
| Plafond annuel pour le taux 2 : 231 € | 7 933 | 9 763 | 11 594 | 13 424 | 15 255 | 1 830,6 |
| Plafond annuel pour le taux 3 : 360 € | 2 799 | 3 445 | 4 091 | 4 737 | 5 383 | 645,9 |

Cf. http://www.education.gouv.fr/cid88/les-aides-financieres-au-college.html

Le taux actuel de 0.3 entre chaque plafond ne me semble plus marcher, il semble se situer entre 23.07% et 23.08%.

**Comment by fpagnoux** [comment]
[PR](https://github.com/openfisca/openfisca-france/pull/339) sent

**Comment by fpagnoux** [comment]
Mis en prod aujourd'hui

**Comment by fpagnoux** [comment]
@helag @mattisg @anne-laurem
On n'a pas défini de communication sur celui-là, est-ce qu'on fait quelque chose ?

Si on veut tester cette mise à jour des barèmes, je suggère qu'on ne le fasse pas sur ludwig, c'est trop lourd. J'ai créé [quelques tests](https://github.com/sgmap/openfisca-france/blob/maj-bourse/openfisca_france/tests/formulas/bourse.yaml) directement en yaml. Je pense que ce format est plus adapté, car il ne pollue pas notre base de vrai tests, et on peut facilement faire du copier/coller pour dupliquer et modifier légèrement les cas.  Le fichier est éditable directement sur github. Je peux vous montrer :)

Est-ce que ça vous paraît à tous faisable d'utiliser ce format à l'avenir quand on est confronté à ce type de cas (beaucoup de tests similaires à créer pour tester beaucoup de situations très proches) ?

**Comment by MattiSG** [comment]
> On n'a pas défini de communication sur celui-là

Meh, c'est un peu tard pour  :-/
Éventuellement, si on faisait un lien avec Bourses, je dis pas, mais là c'est bof.

En fait, de manière générale, la communication sur la fiabilité a de moins en moins de sens puisque ça devient un acquis  ;)

Le format YAML me semble carrément plus adapté. Il pose pour l'instant un problème sur le fait qu'on a tellement communiqué sur Ludwig comme étant la source de vérité sur la fiabilité que ça en devient invisible, mais je pense qu'on devrait se préoccuper de rendre Ludwig compatible avec la représentation de ces tests plutôt qu'autre chose.

La question de l'usabilité se pose donc surtout à @HelaG et @Anne-LaureM (notamment comme porte-parole des experts que nous accompagnons).
