### ISSUE TITLE
Appliquer la sanction "ASF" dans le calcul du RSA

### ISSUE THREAD

**Issue by HelaG** [sgmap/openfisca-france#29]
En tant que potentiel bénéficiaire du RSA,
Je peux correctement évaluer mon droit au RSA en fonction de mon droit à l'ASF

Comm:
- [x] DGCS
- [x] Caf 77

**Comment by HelaG** [comment]
Le RSA est un droit [subsidiaire](http://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074069&idArticle=LEGIARTI000006797194&dateTexte=&categorieLien=cid). Ce qui veut dire que le bénéficiaire potentiel doit faire valoir son droit à l'ASF avant son droit au RSA. 

Le bénéficiaire potentiel du RSA peut demander à être ["dispensé" de son obligation](http://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074069&idArticle=LEGIARTI000027572566) à faire valoir ses droits au président du conseil département (PCD).

Sans cette dispense, si le bénéficiaire potentiel ne fait pas valoir  le PCD applique une "sanction" en soustrayant le montant forfaitaire d'ASF du calcul du RSA.

**Comment by HelaG** [comment]
Quand on détecte une éligibilité potentielle à l'ASF, on la fait apparaitre en résultat et on déduit systématiquement un montant forfaitaire d'ASF du calcul du RSA.

Ce qui n'est pas le cas pour les cas de recette de la Caf:
- https://mes-aides.gouv.fr/tests/559fbff8186ae5620110e2a6/show?keyword=recette
- https://mes-aides.gouv.fr/tests/559f904dd7483c5f013a9b55/show?keyword=recette

**Comment by HelaG** [comment]
@fpagnoux je continue de penser qu'on ne peut pas faire mieux que d'afficher l'éligibilité à l'ASF et le RSA minoré du montant forfaitaire de l'ASF.

Par contre, je pense qu'on a encore un problème sur l'ASF cf [nouveau test de la Caf 44](https://mes-aides.gouv.fr/tests/55f022fa0d70943004ddcca2/show).

**Comment by fpagnoux** [comment]
Sur ce cas, les pensions alimentaires ont été indiquées nulles sur les 3 derniers mois. L'ASF est donc activé. Je pense que c'est une erreur de saisie.

**Comment by fpagnoux** [comment]
Par contre, as-tu vu ce [commentaire](https://github.com/openfisca/openfisca-france/pull/301#issuecomment-138963795) de @benjello ?
Cela risque de complexifier la prise en compte des pensions alimentaires...

**Comment by HelaG** [comment]
C'est pas forcement une erreur de saisie. Les pensions alimentaires, peuvent être versées de façon annuelle par l'ex-conjoint. Auquel cas il n'y a pas créance alimentaire et donc pas d'ASF. 

Pour le cas des pensions alimentaires versées par les parents de la jeune maman, je pense que l'on peut convenir qu'il s'agit d'un cas assez rare pour ne pas affecter la prise en compte nominale des pensions alimentaires versée par un ex-conjoint. A discuter.

**Comment by fpagnoux** [comment]
Dans ce cas, comment différencier une situation où l'ex-conjoint a arrêté
de verser la pension il y a 6 mois, de celle où il la verse annuellement ?

Je suis bien d'accord sur le second point, mais il faudra en discuter avec
openfisca.

**Comment by HelaG** [comment]
Si on détecte une éligibilité on à l'ASF, on demande à la personne de préciser si un juge ou un médiateur à fixer un montant de pension alimentaire :
- Si oui alors, on lui confirme son droit ASF;
- Si non, on lui demande si elle a été dispensé d'engager une actions  pour fixer des PA;
  Si oui on lui donne du RSA sans "sanction ASF". 
  Si non, on l'informe qu'elle devra engager ces démarches dans les 4 mois après l'ouverture du droit.

**Comment by HelaG** [comment]
@fpagnoux : En attente d'infos claires sur les cas de dispense ASF et d'"hors d'Etat", on applique la sanction ASF du montant d'1 forfait?

**Comment by HelaG** [comment]
L'[article R262-10-](http://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=7D13223DCE21CBCC78A28F0B237BC01D.tpdila18v_1?idArticle=LEGIARTI000029006452&cidTexte=LEGITEXT000006074069&dateTexte=20151002&categorieLien=id&oldAction=&nbResultRech=) explique comment prendre en compte l'ASF au montant forfaitaire. 
Il n'est pas spécifié qu'on doit prendre en compte le montant d'1 forfait ASF... L'[art L262-12](http://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074069&idArticle=LEGIARTI000027572566) parle d'une sanction "au plus égal à celui de la créance alimentaire, lorsqu'elle est fixée, ou à celui de l'allocation de soutien familial".  
Et même le différentiel de % pris en compte n'est pas clair, les 1° et les 2° de l'[art L523-3](http://www.legifrance.gouv.fr/affichCode.do;jsessionid=EED32BA2044FE597A4BF0106F0CE6DF0.tpdjo10v_2?idSectionTA=LEGISCTA000006156165&cidTexte=LEGITEXT000006073189&dateTexte=20110828|) disent tous les deux :  "l'enfant est orphelin de père ou de mère ou se trouve dans une situation qui y est assimilée, au sens de l'article L. 523-1"

**Comment by fpagnoux** [comment]
Ok pour moi, on peut implémenter ça rapidement en attente de plus d'information.

**Comment by fpagnoux** [comment]
Décision après point avec @helag :
La sanction ASF étant à la discrétion du PCD, on ne pourra pas l'automatiser. 
On va donc rester sur le fonctionnement actuel, i.e. 

> Quand une personne se déclare isolée, avec enfant, et sans pension alimentaire, on lui propose de l'ASF et un RSA déduit  du montant forfaitaire de l'ASF

**Comment by MattiSG** [comment]
- [x] Documenter dans wiki (lien vers discussion ou synthèse si nécessaire).
- [x] Refuser les tests dépendant d’une décision humaine, en accord avec leur auteur.
