### ISSUE TITLE
Gérer les DOM/TOM

### ISSUE THREAD

**Issue by MattiSG** [sgmap/openfisca-france#3]
En tant que bénéficiaire potentiel résidant dans un DOM/TOM hors Mayotte,
Je peux bénéficier des règles spécifiques à ma situation,
Pour déterminer mon éligibilité et le montant aux prestations CF et AF

**Comment by jdesboeufs** [comment]
Fixed in openfisca/openfisca-france#224 and openfisca/openfisca-france#219

**Comment by MattiSG** [comment]
(sorry for reopening, sorting out how Waffle works)

**Comment by MattiSG** [comment]
https://twitter.com/mesaides/status/600307086434664449
