### ISSUE TITLE
Prendre en compte les personnes hébergées à titre onéreux

### ISSUE THREAD

**Issue by Anne-LaureM** [sgmap/openfisca-france#30]
En tant que bénéficiaire potentiel hébergé à titre onéreux, je dois pouvoir me reconnaitre dans le statut "hébergé" et ne pas me voir appliquer le forfait logement dans le calcul du RSA
- [x] Modifier "Vous êtes occupant à titre gratuit" en "Vous êtes hébergé"
- [x] Si le bénéficiaire potentiel coche le statut "hébergé", afficher la question "Participez-vous aux frais du logement (électricité, gaz...)?"

**Comment by fpagnoux** [comment]
![image](https://cloud.githubusercontent.com/assets/11834997/10198772/d32e3b0e-679d-11e5-98fa-20d1c05dd345.png)

@HelaG @MattiSG @Anne-LaureM, est-ce que cette interface vous paraît adaptée?

**Comment by MattiSG** [comment]
Mmh. Nécessite un test utilisateur.

**Comment by fpagnoux** [comment]
Ça a marché avec Yohan

**Comment by MattiSG** [comment]
- [x] Vérifier la terminologie associée à l’hébergement en foyer (parle-t-on de bail ?). — @HelaG
- [x] Faire apparaître la notion d’apparition sur le bail dans « locataire ». — @MattiSG @Fpagnoux
- [x] Supprimer la condition textuelle « apparaître sur le bail ». — @Fpagnoux
- [ ] Explorer au niveau juridique le cas location longue durée via plateforme de mise en relation numérique (AirBnB…) : contacter Droits d’Urgence et CAF. — @HelaG
- [x] Vérifier la cohérence du parcours « locataire » avec les nouvelles connaissances. — @MattiSG @HelaG @Fpagnoux

**Comment by HelaG** [comment]
Terminologie utilisée en foyer : on parle de contrat de résidence (maison de retraite, foyer social...), de contrat de location et plus rarement de bail. 

J'ai demandé à une amie en foyer qui pour les aides au logement se souvient avoir fourni une attestation de loyer (formulaire de la Caf rempli par le bailleur ou gestionnaire de foyer).

Je propose d'afficher en face (ou en sur texte) de locataire "vous figurez sur le contrat de location ou de résidence".

**Comment by fpagnoux** [comment]
En surtexte : ![image](https://cloud.githubusercontent.com/assets/11834997/10936223/c148cda0-82eb-11e5-9381-89253841dcc2.png)

**Comment by fpagnoux** [comment]
Dans le texte de label : ![image](https://cloud.githubusercontent.com/assets/11834997/10936267/08e0d8c4-82ec-11e5-8608-b15ef5c149e8.png)

**Comment by fpagnoux** [comment]
En face du texte dans un `helpblock` c'est quelque chose qu'on n'a jamais fait sur mes-aides pour des listes à puces, ça demanderait plus de travail.

**Comment by fpagnoux** [comment]
@MattiSG, @HelaG, 
Des idées sur l'implémentation ? Je trouve la deuxième un peu lourde, mais dans la première pas sûr que le bénéficiaire potentiel voit le message. 
@MattiSG, tu es d'accord sur le fait que ce soit trop cher d'investir sur l'intégration de helpblock dans les listes ou pour toi ça vaut le coup ?

**Comment by MattiSG** [comment]
Timebox 1h sur help block dans les listes, et à défaut go solution 1 ?

**Comment by MattiSG** [comment]
- [x] Passer un appel à testeurs sur réseaux. — @MattiSG

**Comment by MattiSG** [comment]
https://twitter.com/mesaides/status/662215852369031168

**Comment by MattiSG** [comment]
Test utilisateur hébergé chez parents : ok.

**Comment by MattiSG** [comment]
Test utilisateur hébergé chez parents : ok. (+1)

**Comment by MattiSG** [comment]
Test utilisateur hébergé chez amis : ok. Le différentiel avec la version actuelle prouve une nette amélioration.

Formulation « Hébergé » validée.

**Comment by MattiSG** [comment]
@HelaG @fpagnoux on n’a pas de test Ludwig sur le sujet ?!

**Comment by HelaG** [comment]
En tant que personne sans domicile stable, je peux être domicilié par la mairie (et pas une association)

**Comment by HelaG** [comment]
Si on a un [test ludwig](https://mes-aides.gouv.fr/tests/55929dc82f56a0fd2f63356b/show?keyword=forfait%20logement).

**Comment by MattiSG** [comment]
> Si on a un test ludwig.

Il mentionne un bénéficiaire « sans domicile stable », je parlais d'un test pour une personne hébergée à titre onéreux  :wink:

**Comment by HelaG** [comment]
Maintenant on en a [un](https://mes-aides.gouv.fr/tests/564f45b4b1fc7b1002c2cfc0/show)!

**Comment by HelaG** [comment]
@MattiSG tu as reçu une réponse de la CNAF à ton mail du 07/09? 
Si oui, ce serait sympa de lui parler de cette petite nouveauté!

**Comment by MattiSG** [comment]
Non, pas eu de réponse. On met ça dans la com  :)

**Comment by MattiSG** [comment]
https://twitter.com/mesaides/status/667774044196970497
