### ISSUE TITLE
Prendre en compte les adultes handicapés à charge dans le calcul de l"APL

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-france#32]
En tant que bénéficiaire potentiel ayant un adulte handicapé à charge,
Cette personne est prise en compte dans le calcul des allocations logement,
Pour que je puisse obtenir une estimation plus juste de mon AL

Explique [ce cas de recette rouge](https://mes-aides.gouv.fr/tests/559fb665f394e1a7011b573a/show)

**Comment by MattiSG** [comment]
Duplicate of sgmap/mes-aides-ui#169.
