### ISSUE TITLE
Prendre en compte les prestations injectées dans le calcul du RSA

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-france#33]
En tant que bénéficiaire potentiel déclarant des prestations, 
Celles-ci sont prises en compte dans le calcul du RSA, 
Pour obtenir une évaluation plus juste du montant de mon RSA

**Comment by fpagnoux** [comment]
Aujourd'hui, le RSA est encore dans l'ancien modèle et utilise les valeurs calculées pour le mois M.

**Comment by fpagnoux** [comment]
Je viens d'implémenter en local chez moi, ça casse 11 tests. Ça vaut le coup de s'y arrêter parce que ça pose des vrais questions sur le fonctionnement du simulateur et sur l'injection des ressources. Pour ouvrir le débat, je vous donne tous les cas que j'ai pu trouvé/imaginé et qui peuvent poser problème.

#### [Cas 1 : primo accédant](https://mes-aides.gouv.fr/tests/55bb70a5f0ac7bb86ba0523d/show?state=pending&state=validated)

Je suis en couple, sans revenu, et j'ai un enfant de 2 ans.
J'ai donc le droit à la PAJE (180€) et au RSA(924€).
Or la PAJE fait partie des ressources prises en compte par le RSA. 
Je ne touche aujourd'hui aucune aide. Je fais une simulation sur mes-aides. 
Qu'est ce que le simulateur doit m'indiquer ?
- **A**: `PAJE = 180€` et `RSA = 738€`. C'est le fonctionnement actuel, dans lequel on déduit les aides calculées du RSA. C'est le montant que je percevrai dans 3 mois, une fois en régime permanent.
- **B**: `PAJE = 180€` et `RSA = 924€`. C'est le potentiel nouveau fonctionnement, dans lequel on ne prend en compte que les ressources déclarées. C'est (sauf si la caf anticipe) le montant que je percevrai le mois prochain si je fais ma demande aujourd'hui.

**Comment by fpagnoux** [comment]
#### Cas 2:  Forfait logement

Je suis locataire, sans revenu
Je suis éligible aux aides logement (400€) et au RSA(514€).
Les AL font partie des ressources prises en compte par le RSA. 
Je ne touche aujourd'hui aucune aide. Je fais une simulation sur mes-aides. 

Qu'est ce que le simulateur doit m'indiquer ?
- **A**: `AL = 400€` et `RSA = 452€`. C'est le fonctionnement actuel, avec déduction du forfait logement. C'est le montant que je percevrai en régime permanent.
- **B**: `AL = 400€` et `RSA = 514€`. Potentiel nouveau fonctionnement. Mais il faudrait savoir si, lorsque la CAF verse AL et RSA, elle ne déduit pas immédiatement un forfait logement.

**Comment by fpagnoux** [comment]
#### [Cas 3 :  Bénéficiaire potentiel vérifiant le montant d'aides qu'il touche déjà](https://mes-aides.gouv.fr/tests/55bb70a5f0ac7bb86ba0523d/show?state=pending&state=validated)

_Variante du 1er_

Je suis en couple, sans revenu, et j'ai un enfant de 2 ans.
Je touche aujourd'hui 180€ de PAJE et 738€ de RSA, car le montant de la PAJE est déduit du RSA.
Je vais sur mes-aides pour regarder à quelles aides j'ai le droit. Par curiosité/pour évaluer la justesse du site/parce que je n'y ai pas pensé, je ne déclare pas les prestations que je touche aujourd'hui, pour voir si mes-aides saura les recalculer.

Je suis surpris de voir que les montants sont différents de ceux que je touche en réalité (RSA surévalué).

=> On peut dire qu'on ignore ce cas car le bénéficiaire potentiel n'a correctement déclaré ses ressources, mais il risque de se produire malgré tout.

**Comment by fpagnoux** [comment]
#### [Cas 4 :   test de recette](https://mes-aides.gouv.fr/tests/55bb70a5f0ac7bb86ba0523d/show?state=pending&state=validated)

_Autre variante du 1er_

Je suis un expert de la CAF, en train d'écrire un test.
Il s'agit du cas d'un couple, sans revenu, avec un enfant de 2 ans.
Il touche aujourd'hui 180€ de PAJE et 738€ de RSA, car le montant de la PAJE est déduit du RSA.
Je veux tester la PAJE et le RSA. Je ne déclare donc pas leurs valeurs, car je veux comparer la réalité aux résultat de mes-aides.

En sortie, mes-aides diffère de mes résultats, car il ne tient pas compte de la déduction de la PAJE du montant du RSA.

=> De même, on peut aussi dire que les ressources n'ont pas été correctement déclarés. Mais certains de nos tests ont été faits avec cette logique. Une solution pourrait être de diviser ces tests en tests plus petits qui ne vérifient qu'une seule prestation à la fois. Mais on perd la capacité à tester une situation dans son ensemble.
C'est sans doute pas le cas le plus gênant.

**Comment by HelaG** [comment]
C'est effectivement un point sur lequel on devrait s'arrêter un moment (éventuellement en discuter avec Jérôme). 

Personnellement, je suis très à l'aise avec les réponses A, qui donne une lecture des droits dans leur ensemble à un instant T (sans séquencement des demandes et des éventuels "avantages" temporaires dont un usager pourrait bénéficier). Mais c'est peut-être simplement que je me suis habituée au fonctionnement actuel du simulateur.

**Comment by fpagnoux** [comment]
#### Cas 5 : sous-ensemble d'une prestation

_Le cas le plus foireux_

J'ai 5 enfants de 20, 17, 11, 7 et 5 ans.
Je touche 610€ d'allocations familiales.
Pour la CAF, ce montant se décompose en un montant de base (463€), plus une majoration liée à l'âge du second et de la troisième (65€) et une allocation forfaitaire pour l’aînée (82€) car c'est la dernière année qu'elle est à ma charge pour la CAF.
Je ne connais pas a priori ces détails, car ce que je vois, c'est le montant  global que me verse la CAF, mes "allocations familiales"
Or, seul le montant de base est déductible du RSA.

Je vais sur mes-aides pour savoir si je suis éligible à d'autres prestations. Je rentre en tant qu'AF le montant global que je connais.

Comment le simulateur peut estimer mon droit au RSA, étant donné qu'il ne connait pas la décomposition de ce montant ? 

Je vois plusieurs solutions possibles : 
- On fait une hypothèse forte du type: 'toutes les AF sont du montant de base'.
- On recalcule ces montants intermédiaires, en l'indiquant d'une manière ou d'une autre au bénéficiaire potentiel.
- On investit dans un algorithme  sur-mesure pour gérer ce problème. Du genre: on recalcule les montants intermédiaires, on les compare au montant total, si on a juste on les ré-injecte, sinon on refait d'autres hypothèses, etc. Ça promet quelque chose de coûteux à mettre en place.

**Comment by HelaG** [comment]
OUCH! Faut vraiment qu'on prenne un moment là dessus!

**Comment by benjello** [comment]
Le montant d'AF de base ne dépend que de la décomposition de la famille et le simulateur le détecte ;-)
En gros dès que je mets que je touche une AF on me demande la composition de ma famille.

**Comment by HelaG** [comment]
Le RSA calculé au mois M prend en compte le montant de prestations que l'usager déclare continuer à percevoir au mois M, à l'exception des agrégats (type AF base / majoré / forfait). 
La prises en compte des agrégats dans le RSA nécessite de connaitre la décomposition exacte (montant de base/majoration) de ces agrégats - l'usager n'en ayant pas connaissance, il est plus sûr de recalculer ces agrégats.

**Comment by HelaG** [comment]
- [x] [wiki](https://wiki.openfisca.fr/index.php/RSA#Ressources)
