### ISSUE TITLE
N'appliquer au maximum qu'une seule sanction ASF

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-france#34]
En tant que bénéficiaire potentiel isolé.e sanctionné.e par un ASF fictif au titre de plusieurs enfants, 
Le montant de RSA que j'obtiens ne prend en compte qu'une seule pénalité,
Pour obtenir une évaluation plus juste de mon RSA

**Comment by fpagnoux** [comment]
Point évoqué par la CAF, **à confirmer**.
Il semble que la sanction appliquée ne corresponde en général qu'à une seul ASF, et ne soit pas proportionnelle au nombre d'enfants concernés.

**Comment by HelaG** [comment]
Connected to sgmap/openfisca-france#29

**Comment by HelaG** [comment]
L'[article R262-10-](http://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=7D13223DCE21CBCC78A28F0B237BC01D.tpdila18v_1?idArticle=LEGIARTI000029006452&cidTexte=LEGITEXT000006074069&dateTexte=20151002&categorieLien=id&oldAction=&nbResultRech=) précise qu'on doit bien prendre en compte d'ASF "pour chaque enfant".
