### ISSUE TITLE
Prendre en compte les revenus N-2 des enfants

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-france#35]
En tant que bénéficiaire potentiel hébergeant sous mon toit des enfants percevant des ressources, 
Leurs revenus (y compris N-2) sont pris en comptes dans mon calcul des AL, 
Pour obtenir une évaluation plus juste de mes AL

**Comment by fpagnoux** [comment]
Vu sur un dossier CAF : 

> Deux enfants salariés, mais trop vieux pour être à charge pour les AL.
> La CAF ajoute un montant de 2175€ aux revenus des parents.
> Ce montant est bien inférieur aux revenus réels des enfants, donc il est probable que ce soit forfaitaire.

**Comment by HelaG** [comment]
[Test prise en compte des ressources des enfants](https://mes-aides.gouv.fr/acceptance-tests/54ad549a8b7d192c16f020ae/show)
[Test de recette Caf77](https://mes-aides.gouv.fr/acceptance-tests/55e69e788f08059b0442d13c/show?keyword=recette)

**Comment by fpagnoux** [comment]
Il y a un abattement documenté sur le [wiki](https://wiki.openfisca.fr/index.php/Allocations_logement#Abattement_enfants_et_personnes_.C3.A2g.C3.A9es).
L'âge de l'enfant n'importe pas, je renomme l'issue. Par contre, il y a un facteur obscur de 1.25 dans la loi.

**Comment by fpagnoux** [comment]
@HelaG : dans le wiki on peut lire:

> Abattement de 11134,18 euros sur les ressources perçues par :
> - Les enfants du demandeur ou du conjoint
> - Les ascendants du demandeur ou de son conjoint âgés d'au moins 65 ans ou 60 ans en cas d'inaptitude au travail

Je n'arrive pas à trouver de référence légale officielle pour ce chiffre. Tu sais d'où il vient ? J'aimerais en particulier savoir s'il n'a pas changé depuis...

**Comment by fpagnoux** [comment]
Ma conjecture est que ce chiffre est 1.25 \* [ce paramètre](http://legislation.openfisca.fr/parameters/minim.aspa.plaf_seul). Ce qui paraît tordu, vu que ça parle d'ASPA, mais ça a l'air de coller pour 2011.

**Comment by fpagnoux** [comment]
Ok, je confirme que c'est bien basé sur l'ASPA.

**Comment by benjello** [comment]
@fpagnoux as-tu une référence législative ?

**Comment by fpagnoux** [comment]
Mergé et déployé
