### ISSUE TITLE
Diviser par 2 la majoration pour âge en cas de garde alternée

### ISSUE THREAD

**Issue by HelaG** [sgmap/openfisca-france#37]
En tant que parent d'un enfant de plus 14 ans en garde alternée,
Je peux avoir une évaluation exacte du montant de mes AF

[cf. Art. 521-4 du CSS](http://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=6DB9AE9F8E1126882C53FDBD583919B1.tpdila23v_1?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000006750611&dateTexte=&categorieLien=cid)

**Comment by HelaG** [comment]
Tests rouges [1](https://mes-aides.gouv.fr/tests/5631ffd49506438345b55b10/show?keyword=af&keyword=garde%20altern%C3%A9e) et [2](https://mes-aides.gouv.fr/tests/563227d6c13af18e45e5cea0/show?keyword=af&keyword=garde%20altern%C3%A9e)

**Comment by fpagnoux** [comment]
Wiki à mettre à jour
