### ISSUE TITLE
Mise à jour des taux de cotisation sociale auto entrepreneurs

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-france#4]
Les taux dans le fichier de paramètres sont eux de 2014, et ils ont été ré-évalués en 2015

**Comment by fpagnoux** [comment]
Les taux dans le fichier de paramètres sont eux de 2014, et ils ont été ré-évalués en 2015

**Comment by MattiSG** [comment]
openfisca/openfisca-france#226 has been merged.

@fpagnoux This is still marked as waiting for external action. Is it really the case?

**Comment by fpagnoux** [comment]
Nope, moved to Deploiement ;)

**Comment by MattiSG** [comment]
:shipit:
