### ISSUE TITLE
Erreur API situations

### ISSUE THREAD

**Issue by GesJeremie** [sgmap/openfisca-france#47]
Url: https://mes-aides.gouv.fr/telecharger-formulaires/rsa

Après simulation des aides, lors de la dernière étape, lorsque je veux télécharger le formulaire de demande, l'API me retourne une erreur:

```
Oops, an error occured
This exception has been logged with id 6ondon1lf.
```

**Comment by MattiSG** [comment]
Bonjour @GesJeremie et merci beaucoup pour ce retour de bug !

Le préremplissage des formulaires est effectivement instable. Nous allons explorer ce sujet plus en détails ici : sgmap/mes-aides-ui#238 (le problème est lié à Mes Aides et non à OpenFisca, simple redirection administrative  ;)  ).
