### ISSUE TITLE
Calculer le revenu imposable

### ISSUE THREAD

**Issue by MattiSG** [sgmap/openfisca-france#5]
En tant que bénéficiaire potentiel de l'ASS,
Je peux estimer mes droits sur la base de mon revenu imposable,
Pour déterminer le montant de la prestation de manière plus précise

Origine : DGEFP

---

@eraviart : y a-t-il eu une amélioration de performances du calcul d'inversion de net vers imposable ?
@benjello : à défaut, quelle approximation peut-on faire de manière raisonnable ?

**Comment by eraviart** [comment]
Pas d'amélioration des performances, mais ce n'est pas le principal problème : l'inversion numérique ne converge pas toujours.
