### ISSUE TITLE
Intégrer correctement les ressources du conjoint dans la base ressource pour l'ASS

### ISSUE THREAD

**Issue by MattiSG** [sgmap/openfisca-france#6]
La base ressource pour déterminer l'éligibilité à l'ASS contient les revenus de substitution (ARE, ASS, IJSS, retraite)  du conjoint. Les revenus d'activité du conjoint sont abattus de 30% s'ils ont été interrompus.

**Comment by MattiSG** [comment]
| éligibilité demandeur | éligibilité conjoint | conjoint touche déjà | calcul |
| --- | --- | --- | --- |
| - | - | - | - |
| + | - | - | + |
| + | + | - | calcul d’abord pour demandeur, puis intégration de l’ASS demandeur dans base ressource conjoint |
| + | + | + | intégration de l’ASS conjoint dans la base ressource demandeur |
| - | + | + | - |
| - | + | - | les résultats pour le conjoint n’étant pas calculés, aucun impact |

**Comment by MattiSG** [comment]
Solution alternative : remonter un cas de non-calculabilité si les deux sont éligibles.

**Comment by MattiSG** [comment]
Redéfinition de cette story en plusieurs. Je mettrai des liens vers les nouvelles.

**Comment by MattiSG** [comment]
@fpagnoux Où en est-on avec cette redéfinition ?  :)

**Comment by fpagnoux** [comment]
Implémentée, je rajoute quelques tests yaml et j'envoie la PR

**Comment by MattiSG** [comment]
:muscle:

**Comment by Anne-LaureM** [comment]
Communication faite à Pôle emploi/DGEFP
