### ISSUE TITLE
TNS (travailleurs non salariés)

### ISSUE THREAD

**Issue by laem** [sgmap/openfisca-france#60]
Il y a quelques variables à propos des TNS dans le code, mais ça semble très partiel. Est-ce seulement ce qui est nécessaire pour le calcul des prestations / mes-aides ? @benjello @fpagnoux

**Comment by benjello** [comment]
En fait les variables liées aux TNS sont en double:
- Certains ont été rajoutées par @jdesboeufs de façon ad-hoc au début de mes aides dans le rush
- D'autres sont présentes comme variables liées à l'impôt sur le revenu

Et oui, il faudrait uniformiser tout cela.

**Comment by fpagnoux** [comment]
Oui, mes-aides et le calcul de l'impôts sont basés chacun sur leurs propres variables...

**Comment by MattiSG** [comment]
Doublon de https://github.com/openfisca/openfisca-france/issues/564.
