### ISSUE TITLE
Prendre en compte la prime forfaitaire mensuelle pour la reprise d’activité dans la PPA

### ISSUE THREAD

**Issue by HelaG** [sgmap/openfisca-france#61]
En tant que potentielle bénéficiaire de la prime forfaitaire mensuelle pour la reprise d’activité 

Je peux avoir une bonne évaluation de la PPA.

La Prime forfaitaire mensuelle pour la reprise d’activité entre dans la BR de la PPA comme l'ASS (revenu de substitution).
- [ ] Mail DGEFP 21/04

**Comment by fpagnoux** [comment]
Doublon de Doublon de sgmap/mes-aides-ui#274. Traité.
