### ISSUE TITLE
Déterminer les interactions des bourses de lycée

### ISSUE THREAD

**Issue by MattiSG** [sgmap/openfisca-france#64]
Avec les autres prestations nationales.

**Comment by fpagnoux** [comment]
- [x] Pas prises en compte pour le RSA
- [x] Pas prises en compte pour la PPA
- [x] Pas prises en compte pour la CMU/ACS
- [x] ASS: Exclu car non imposable
- [x] PF: Exclu car non imposable
- [x] ASI et ASIA: Exclu

**Comment by fpagnoux** [comment]
La bourse de collège n'est impliquée dans aucune interaction. Tout est donc en ordre.
