### ISSUE TITLE
Déterminer les interactions de l'ASI

### ISSUE THREAD

**Issue by MattiSG** [sgmap/openfisca-france#65]
Avec les autres prestations nationales.

**Comment by fpagnoux** [comment]
- [x] RSA: Prise en compte à taux plein
- [x] PPA: Prise en compte à taux plein 
- [x] CMU/ACS: Prise en compte à taux plein
- [x] ASS: Exclu car non imposable
- [x] PF: Exclu car non imposable
- [x] Bourses: Exclu car non imposable
- [x] ASPA: 
  - [x] L'ASI est incompatible avec l'ASPA, elle cesse d'être versée dès que la personne a droit à l'ASPA.
  - [x] L'ASI du conjoint n'est pas prise en compte dans la BR, mais le fait que le conjoint y ait le droit a un impact sur le montant final.
- [x] AAH: 
  -  [x] L'ASI du demandeur est prise en compte dans la BR de l'AAH. L'ASI du conjoint est ignorée (**non implémenté à ce jour**)
  -  [x] L'AAH du conjoint est prise en compte s'il n'est pas lui même éligible à l'ASPA ou à l'ASI (ces deux derniers cas sont très marginaux).

**Comment by MattiSG** [comment]
Ce qui n'est pas coché est en attente de confirmation par le responsable ou en attente d'implémentation dans OpenFisca ?
Si c'est le second cas, fermer cette issue et ouvrir des issues plus spécifiques pour l'implémentation des règles manquantes.

**Comment by fpagnoux** [comment]
Il nous reste l'interaction ASI/AAH

**Comment by fpagnoux** [comment]
http://www.legislation.cnav.fr/Pages/texte.aspx?Nom=LE_MIN_19031982

**Comment by fpagnoux** [comment]
> l'allocation supplémentaire n'est pas passible de l'impôt sur le revenu et de ce fait n'a pas à être prise en considération lorsqu'elle est versée au conjoint pour l'examen de la condition de ressources applicable à l'allocation aux adultes handicapés.
