### ISSUE TITLE
Déterminer les interactions de l'AAH

### ISSUE THREAD

**Issue by MattiSG** [sgmap/openfisca-france#66]
Avec les autres prestations nationales.

**Comment by fpagnoux** [comment]
- [x] RSA: Prise en compte à taux plein
- [x] PPA: Prise en compte à taux plein OU comme un revenu d'activité  (suivant la valeur du revenu d'activité hors AAH)
- [x] CMU/ACS: Prise en compte à taux plein
- [x] ASS: Exclu car non imposable
- [x] PF: Exclu car non imposable
- [x] Bourses: Exclu car non imposable
- [x] ASPA: 
  -  [x] L'AAH est incompatible avec une pension de vieillesse, elle cesse d'être versée dès que la personne a droit à l'ASPA.
  -  [x] L'AAH du conjoint est pris en compte s'il n'est pas titulaire d'une pension d'invalidité ou de vieillesse.
- [x] ASI: voir #65

**Comment by MattiSG** [comment]
Ce qui n'est pas coché est en attente de confirmation par le responsable ou en attente d'implémentation dans OpenFisca ?
Si c'est le second cas, fermer cette issue et ouvrir des issues plus spécifiques pour l'implémentation des règles manquantes.
