### ISSUE TITLE
Supprimer les conditions spécifiques TNS

### ISSUE THREAD

**Issue by MattiSG** [sgmap/openfisca-france#67]
Pour le RSA et la prime d'activité :
- [x] Supprimer la condition de n'avoir aucun salarié pour les TNS.
- [x] Supprimer les plafonds de CA spécifiques TNS.

Prise d'effet au 01/01/2017.

**Comment by fpagnoux** [comment]
Done by https://github.com/openfisca/openfisca-france/pull/646
