### ISSUE TITLE
Ne plus prendre la moyenne des revenus non professionnels et exceptionnels

### ISSUE THREAD

**Issue by MattiSG** [sgmap/openfisca-france#68]
La base de ressources du RSA reste la même, mais le mode de calcul pour les revenus non professionnels ainsi que des revenus exceptionnels (primes, 13ème mois…) passe à un mode avec un montant intermédiaire (sur le modèle de la « PPA fictive ») pour chaque mois, le montant final étant la moyenne des trois montants intermédiaires.

**Comment by fpagnoux** [comment]
Done by https://github.com/openfisca/openfisca-france/pull/646
