### ISSUE TITLE
Éligibilité ASPA vs. RSA

### ISSUE THREAD

**Issue by MattiSG** [sgmap/openfisca-france#7]
Un retraité se voit proposer le RSA plutôt que l'ASPA, alors que ce devrait être l'inverse.

@Anne-LaureM : vérifier les règles de subsidiarité ou cumul (a priori en cas d'ASPA < RSA).

Source : tests usager 13/05.
Tests : [Ludwig](https://mes-aides.gouv.fr/tests/55532045a048a15d31f46e55/show).
### Communication
- [x] wiki

**Comment by MattiSG** [comment]
Pourrait être tout bêtement la case "retraité" non prise en compte.

**Comment by Anne-LaureM** [comment]
Non cumul des 2 allocations : Le droit à la part de RSA socle (RSA socle seul ou RSA socle + activité) est subordonné à la condition que le bénéficiaire et les personnes composant le foyer fassent valoir leurs droits à l'ASPA

**Comment by Anne-LaureM** [comment]
Si la personne se déclare "retraité" il faut donc afficher automatiquement de l'ASPA et non pas du RSA

**Comment by Anne-LaureM** [comment]
En faisant quelques simu, je remarque que c'est uniquement lorsque l'usager déclare percevoir une pension de retraite que l'ASPA s'affiche.  Si il déclare 0 ressource ou des ressources d'une autre nature (salaire, pension alimentaire...) c'est le RSA qui s'affiche.

**Comment by fpagnoux** [comment]
Je confirme que dans le code, l'éligibilité à l'ASPA est conditionnée au versement d'une pension de retraite ou d'invalidité. 
Je vais changer le comportement pour que si la case retraitée a été cochée, on ignore cette condition.

**Comment by fpagnoux** [comment]
Autre question liée :
Si le demandeur a plus que l'âge légal pour bénéficier de l'ASPA, mais ne touche pas de pension, et ne se déclare pas comme retraité dans le premier écran, on ne lui propose pas d'ASPA mais du RSA.  Vu son âge, il devrait pourtant avoir droit à l'ASPA. 

Est-ce que c'est une situation qui vous paraît réaliste  ? Je peux imaginer que quelqu'un qui ne touche pas de pension de retraite de se considère pas comme retraité, mais je connais mal le sujet. 

Merci !

**Comment by fpagnoux** [comment]
Vu avec Héla et Anne-Laure : 
Une personne de plus de 65 ans doit toujours se faire proposer de l'ASPA plutôt que du RSA. Un disclaimer à la fin de la simulation rappellera  au demandeur qu'une condition préalable est d'avoir liquidé ses droits à la retraite. 
On ne prendra donc plus en compte la condition "être retraité".

**Comment by fpagnoux** [comment]
Done, reste la phrase à ajouter pour indiquer au demandeur qu'il doit avoir liquidé ses droits à la retraite.

**Comment by Anne-LaureM** [comment]
En fin de simu, ajouter la phrase:
"Pour prétendre à l'ASPA, vous devez, ainsi que votre conjoint, avoir demandé l'attribution de toutes vos retraites personnelles et de réversion à tous les régimes"

**Comment by Anne-LaureM** [comment]
Vérifier la règle suivante:
Age minimal pour bénéficier de l'ASPA est abaissé à 62 ans pour les personnes inaptes au travail et pour les personnes dont le taux de handicap est égal ou supérieur à 50%

**Comment by fpagnoux** [comment]
Je sors les deux précédents points dans des issues séparées, sinon on commence à digresser un peu trop ;)

**Comment by HelaG** [comment]
J'ai supprimé le test usager sur ce bug (il était rouge parce que le montant d'ASPA que m'avait communiqué l'usager était approximatif). 

Mais on a une super histoire à raconter sur cette implem!

**Comment by MattiSG** [comment]
> Je sors les deux précédents points dans des issues séparées, sinon on commence à digresser un peu trop ;)

:+1:
