### ISSUE TITLE
Éligibilité des propriétaires aux Aides au logement

### ISSUE THREAD

**Issue by MattiSG** [sgmap/openfisca-france#8]
Vérifier qu'un propriétaire non primo-accédant est réellement potentiellement éligible aux AL.

S'il ne l'est pas, mettre à jour la non-calculabilité et afficher une inéligibilité.
### Communication
- [x] wiki
- [ ] tweet

**Comment by HelaG** [comment]
Un [propriétaire](http://vosdroits.service-public.fr/particuliers/F32384.xhtml), non primo-accédant, n'est pas éligible aux AL. 

Une personne qui jouit de l'usufruit sur le logement ou qui détient des parts dans une SCI propriétaire du logement n'est pas éligible aux AL. [cf alinéa VIII art. L 542-2 CSS](http://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000006743358&dateTexte=&categorieLien=cid)

Par dérogation, si le bénéficiaire (ou son conjoint, ou un de leur ascendant) ne détient pas plus de 10% des parts de propriété ou d'usufruit il peut être éligible. [cf. dernier paragraphe de l'art. R 351-1 CCH](http://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=7A743DEBA0E54A9DB6ADC41C6022519F.tpdila23v_3?cidTexte=LEGITEXT000006074096&idArticle=LEGIARTI000029543215&dateTexte=20150527&categorieLien=id#LEGIARTI000029543215).

**Comment by HelaG** [comment]
Aujourd'hui quand l'utilisateur déclare être propriétaire / en location accession, on lui demande s'il est primo-accédant, s'il répond "Non", il poursuit sa simulation et des AL apparaîssent en résultat (en non calculable car propriétaire). 

Pour être exact, il faudrait que les AL n'apparaissent pas en résultat. 

Pour être entièrement exaustif, et traiter le cas dérogatoire, on pourrait préciser la question du % de parts de propriété ou d'usufruit dans la page patrimoine.

**Comment by HelaG** [comment]
Pas de tweet sur une non-éligibilité -> DONE
